//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 2/10/2015 11:06:04 PM
namespace LightSwitchApplication.Implementation
{
    
    /// <summary>
    /// There are no comments for ApplicationData in the schema.
    /// </summary>
    public partial class ApplicationData : global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext
    {
        /// <summary>
        /// Initialize a new ApplicationData object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ApplicationData(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "LightSwitchApplication", "LightSwitchApplication.Implementation");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("LightSwitchApplication.Implementation", global::System.StringComparison.Ordinal))
            {
                return string.Concat("LightSwitchApplication.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Collaborateurs in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Collaborateur> Collaborateurs
        {
            get
            {
                if ((this._Collaborateurs == null))
                {
                    this._Collaborateurs = base.CreateQuery<Collaborateur>("Collaborateurs");
                }
                return this._Collaborateurs;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Collaborateur> _Collaborateurs;
        /// <summary>
        /// There are no comments for Commercials in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Commercial> Commercials
        {
            get
            {
                if ((this._Commercials == null))
                {
                    this._Commercials = base.CreateQuery<Commercial>("Commercials");
                }
                return this._Commercials;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Commercial> _Commercials;
        /// <summary>
        /// There are no comments for Missions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Mission> Missions
        {
            get
            {
                if ((this._Missions == null))
                {
                    this._Missions = base.CreateQuery<Mission>("Missions");
                }
                return this._Missions;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Mission> _Missions;
        /// <summary>
        /// There are no comments for Collaborateurs in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCollaborateurs(Collaborateur collaborateur)
        {
            base.AddObject("Collaborateurs", collaborateur);
        }
        /// <summary>
        /// There are no comments for Commercials in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCommercials(Commercial commercial)
        {
            base.AddObject("Commercials", commercial);
        }
        /// <summary>
        /// There are no comments for Missions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToMissions(Mission mission)
        {
            base.AddObject("Missions", mission);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices xmlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataserv" +
                "ices/metadata\" m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\"><Schema " +
                "xmlns:annotation=\"http://schemas.microsoft.com/ado/2009/02/edm/annotation\" Names" +
                "pace=\"LightSwitchApplication\" Alias=\"Self\" xmlns=\"http://schemas.microsoft.com/a" +
                "do/2008/09/edm\"><EntityType Name=\"Collaborateur\"><Key><PropertyRef Name=\"Id\" /><" +
                "/Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" annotation:StoreGener" +
                "atedPattern=\"Identity\" /><Property Name=\"nom\" Type=\"Edm.String\" Nullable=\"false\"" +
                " MaxLength=\"255\" /><Property Name=\"prenom\" Type=\"Edm.String\" Nullable=\"false\" Ma" +
                "xLength=\"255\" /><Property Name=\"email\" Type=\"Edm.String\" Nullable=\"false\" MaxLen" +
                "gth=\"255\" /><Property Name=\"portable\" Type=\"Edm.String\" MaxLength=\"255\" /><Prope" +
                "rty Name=\"Portrait\" Type=\"Edm.Binary\" MaxLength=\"Max\" /><Property Name=\"CreatedB" +
                "y\" Type=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"Created\" Type=\"Edm.DateTi" +
                "meOffset\" /><Property Name=\"ModifiedBy\" Type=\"Edm.String\" MaxLength=\"255\" /><Pro" +
                "perty Name=\"Modified\" Type=\"Edm.DateTimeOffset\" /><Property Name=\"RowVersion\" Ty" +
                "pe=\"Edm.Binary\" Nullable=\"false\" ConcurrencyMode=\"Fixed\" annotation:StoreGenerat" +
                "edPattern=\"Computed\" /><NavigationProperty Name=\"Missions\" Relationship=\"LightSw" +
                "itchApplication.Mission_Collaborateur\" ToRole=\"Mission\" FromRole=\"Collaborateur\"" +
                " /></EntityType><EntityType Name=\"Commercial\"><Key><PropertyRef Name=\"Id\" /></Ke" +
                "y><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" annotation:StoreGenerate" +
                "dPattern=\"Identity\" /><Property Name=\"nom\" Type=\"Edm.String\" Nullable=\"false\" Ma" +
                "xLength=\"255\" /><Property Name=\"prenom\" Type=\"Edm.String\" Nullable=\"false\" MaxLe" +
                "ngth=\"255\" /><Property Name=\"Grade\" Type=\"Edm.String\" Nullable=\"false\" MaxLength" +
                "=\"255\" /><Property Name=\"CreatedBy\" Type=\"Edm.String\" MaxLength=\"255\" /><Propert" +
                "y Name=\"Created\" Type=\"Edm.DateTimeOffset\" /><Property Name=\"ModifiedBy\" Type=\"E" +
                "dm.String\" MaxLength=\"255\" /><Property Name=\"Modified\" Type=\"Edm.DateTimeOffset\"" +
                " /><Property Name=\"RowVersion\" Type=\"Edm.Binary\" Nullable=\"false\" ConcurrencyMod" +
                "e=\"Fixed\" annotation:StoreGeneratedPattern=\"Computed\" /><NavigationProperty Name" +
                "=\"Missions\" Relationship=\"LightSwitchApplication.Mission_Commercial\" ToRole=\"Mis" +
                "sion\" FromRole=\"Commercial\" /></EntityType><EntityType Name=\"Mission\"><Key><Prop" +
                "ertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" " +
                "annotation:StoreGeneratedPattern=\"Identity\" /><Property Name=\"dateDebut\" Type=\"E" +
                "dm.DateTime\" Nullable=\"false\" /><Property Name=\"dateFin\" Type=\"Edm.DateTime\" /><" +
                "Property Name=\"nomClient\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"255\" /><" +
                "Property Name=\"posteOccupe\" Type=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"" +
                "Mission_Commercial\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Mission_" +
                "Collaborateur\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"CreatedBy\" Ty" +
                "pe=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"Created\" Type=\"Edm.DateTimeOff" +
                "set\" /><Property Name=\"ModifiedBy\" Type=\"Edm.String\" MaxLength=\"255\" /><Property" +
                " Name=\"Modified\" Type=\"Edm.DateTimeOffset\" /><Property Name=\"RowVersion\" Type=\"E" +
                "dm.Binary\" Nullable=\"false\" ConcurrencyMode=\"Fixed\" annotation:StoreGeneratedPat" +
                "tern=\"Computed\" /><NavigationProperty Name=\"Commercial\" Relationship=\"LightSwitc" +
                "hApplication.Mission_Commercial\" ToRole=\"Commercial\" FromRole=\"Mission\" /><Navig" +
                "ationProperty Name=\"Collaborateur\" Relationship=\"LightSwitchApplication.Mission_" +
                "Collaborateur\" ToRole=\"Collaborateur\" FromRole=\"Mission\" /></EntityType><Associa" +
                "tion Name=\"Mission_Collaborateur\"><End Role=\"Collaborateur\" Type=\"LightSwitchApp" +
                "lication.Collaborateur\" Multiplicity=\"1\" /><End Role=\"Mission\" Type=\"LightSwitch" +
                "Application.Mission\" Multiplicity=\"*\" /><ReferentialConstraint><Principal Role=\"" +
                "Collaborateur\"><PropertyRef Name=\"Id\" /></Principal><Dependent Role=\"Mission\"><P" +
                "ropertyRef Name=\"Mission_Collaborateur\" /></Dependent></ReferentialConstraint></" +
                "Association><Association Name=\"Mission_Commercial\"><End Role=\"Commercial\" Type=\"" +
                "LightSwitchApplication.Commercial\" Multiplicity=\"1\" /><End Role=\"Mission\" Type=\"" +
                "LightSwitchApplication.Mission\" Multiplicity=\"*\" /><ReferentialConstraint><Princ" +
                "ipal Role=\"Commercial\"><PropertyRef Name=\"Id\" /></Principal><Dependent Role=\"Mis" +
                "sion\"><PropertyRef Name=\"Mission_Commercial\" /></Dependent></ReferentialConstrai" +
                "nt></Association><EntityContainer Name=\"ApplicationData\" m:IsDefaultEntityContai" +
                "ner=\"true\"><EntitySet Name=\"Collaborateurs\" EntityType=\"LightSwitchApplication.C" +
                "ollaborateur\" /><EntitySet Name=\"Commercials\" EntityType=\"LightSwitchApplication" +
                ".Commercial\" /><EntitySet Name=\"Missions\" EntityType=\"LightSwitchApplication.Mis" +
                "sion\" /><AssociationSet Name=\"Mission_Collaborateur\" Association=\"LightSwitchApp" +
                "lication.Mission_Collaborateur\"><End Role=\"Collaborateur\" EntitySet=\"Collaborate" +
                "urs\" /><End Role=\"Mission\" EntitySet=\"Missions\" /></AssociationSet><AssociationS" +
                "et Name=\"Mission_Commercial\" Association=\"LightSwitchApplication.Mission_Commerc" +
                "ial\"><End Role=\"Commercial\" EntitySet=\"Commercials\" /><End Role=\"Mission\" Entity" +
                "Set=\"Missions\" /></AssociationSet><FunctionImport Name=\"MissionByClient\" ReturnT" +
                "ype=\"Collection(LightSwitchApplication.Mission)\" EntitySet=\"Missions\" m:HttpMeth" +
                "od=\"GET\"><Parameter Name=\"pNomClient\" Type=\"Edm.String\" Mode=\"In\" /></FunctionIm" +
                "port><FunctionImport Name=\"MissionEnCours\" ReturnType=\"Collection(LightSwitchApp" +
                "lication.Mission)\" EntitySet=\"Missions\" m:HttpMethod=\"GET\" /><FunctionImport Nam" +
                "e=\"Microsoft_LightSwitch_GetCanInformation\" ReturnType=\"Edm.String\" m:HttpMethod" +
                "=\"GET\"><Parameter Name=\"dataServiceMembers\" Type=\"Edm.String\" Mode=\"In\" /></Func" +
                "tionImport></EntityContainer></Schema></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.Collaborateur in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Collaborateurs")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Collaborateur : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Collaborateur object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="nom">Initial value of nom.</param>
        /// <param name="prenom">Initial value of prenom.</param>
        /// <param name="email">Initial value of email.</param>
        /// <param name="rowVersion">Initial value of RowVersion.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Collaborateur CreateCollaborateur(int ID, string nom, string prenom, string email, byte[] rowVersion)
        {
            Collaborateur collaborateur = new Collaborateur();
            collaborateur.Id = ID;
            collaborateur.nom = nom;
            collaborateur.prenom = prenom;
            collaborateur.email = email;
            collaborateur.RowVersion = rowVersion;
            return collaborateur;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property nom in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string nom
        {
            get
            {
                return this._nom;
            }
            set
            {
                this.OnnomChanging(value);
                if (object.Equals(this.nom, value))
                {
                    return;
                }
                this._nom = value;
                this.OnnomChanged();
                this.OnPropertyChanged("nom");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _nom;
        partial void OnnomChanging(string value);
        partial void OnnomChanged();
        /// <summary>
        /// There are no comments for Property prenom in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string prenom
        {
            get
            {
                return this._prenom;
            }
            set
            {
                this.OnprenomChanging(value);
                if (object.Equals(this.prenom, value))
                {
                    return;
                }
                this._prenom = value;
                this.OnprenomChanged();
                this.OnPropertyChanged("prenom");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _prenom;
        partial void OnprenomChanging(string value);
        partial void OnprenomChanged();
        /// <summary>
        /// There are no comments for Property email in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string email
        {
            get
            {
                return this._email;
            }
            set
            {
                this.OnemailChanging(value);
                if (object.Equals(this.email, value))
                {
                    return;
                }
                this._email = value;
                this.OnemailChanged();
                this.OnPropertyChanged("email");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _email;
        partial void OnemailChanging(string value);
        partial void OnemailChanged();
        /// <summary>
        /// There are no comments for Property portable in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string portable
        {
            get
            {
                return this._portable;
            }
            set
            {
                this.OnportableChanging(value);
                if (object.Equals(this.portable, value))
                {
                    return;
                }
                this._portable = value;
                this.OnportableChanged();
                this.OnPropertyChanged("portable");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _portable;
        partial void OnportableChanging(string value);
        partial void OnportableChanged();
        /// <summary>
        /// There are no comments for Property Portrait in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] Portrait
        {
            get
            {
                if ((this._Portrait != null))
                {
                    return ((byte[])(this._Portrait.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnPortraitChanging(value);
                if (object.Equals(this.Portrait, value))
                {
                    return;
                }
                this._Portrait = value;
                this.OnPortraitChanged();
                this.OnPropertyChanged("Portrait");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _Portrait;
        partial void OnPortraitChanging(byte[] value);
        partial void OnPortraitChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                if (object.Equals(this.CreatedBy, value))
                {
                    return;
                }
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property Created in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                if (object.Equals(this.Created, value))
                {
                    return;
                }
                this._Created = value;
                this.OnCreatedChanged();
                this.OnPropertyChanged("Created");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Created;
        partial void OnCreatedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                if (object.Equals(this.ModifiedBy, value))
                {
                    return;
                }
                this._ModifiedBy = value;
                this.OnModifiedByChanged();
                this.OnPropertyChanged("ModifiedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property Modified in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return this._Modified;
            }
            set
            {
                this.OnModifiedChanging(value);
                if (object.Equals(this.Modified, value))
                {
                    return;
                }
                this._Modified = value;
                this.OnModifiedChanged();
                this.OnPropertyChanged("Modified");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Modified;
        partial void OnModifiedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedChanged();
        /// <summary>
        /// There are no comments for Property RowVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// There are no comments for Missions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Mission> Missions
        {
            get
            {
                this.@__Missions.EnsureValueInitialized();
                return this._Missions;
            }
            set
            {
                this._Missions = value;
                this.OnPropertyChanged("Missions");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Mission> _Missions = new global::System.Data.Services.Client.DataServiceCollection<Mission>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.Commercial in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Commercials")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Commercial : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Commercial object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="nom">Initial value of nom.</param>
        /// <param name="prenom">Initial value of prenom.</param>
        /// <param name="grade">Initial value of Grade.</param>
        /// <param name="rowVersion">Initial value of RowVersion.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Commercial CreateCommercial(int ID, string nom, string prenom, string grade, byte[] rowVersion)
        {
            Commercial commercial = new Commercial();
            commercial.Id = ID;
            commercial.nom = nom;
            commercial.prenom = prenom;
            commercial.Grade = grade;
            commercial.RowVersion = rowVersion;
            return commercial;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property nom in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string nom
        {
            get
            {
                return this._nom;
            }
            set
            {
                this.OnnomChanging(value);
                if (object.Equals(this.nom, value))
                {
                    return;
                }
                this._nom = value;
                this.OnnomChanged();
                this.OnPropertyChanged("nom");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _nom;
        partial void OnnomChanging(string value);
        partial void OnnomChanged();
        /// <summary>
        /// There are no comments for Property prenom in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string prenom
        {
            get
            {
                return this._prenom;
            }
            set
            {
                this.OnprenomChanging(value);
                if (object.Equals(this.prenom, value))
                {
                    return;
                }
                this._prenom = value;
                this.OnprenomChanged();
                this.OnPropertyChanged("prenom");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _prenom;
        partial void OnprenomChanging(string value);
        partial void OnprenomChanged();
        /// <summary>
        /// There are no comments for Property Grade in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Grade
        {
            get
            {
                return this._Grade;
            }
            set
            {
                this.OnGradeChanging(value);
                if (object.Equals(this.Grade, value))
                {
                    return;
                }
                this._Grade = value;
                this.OnGradeChanged();
                this.OnPropertyChanged("Grade");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Grade;
        partial void OnGradeChanging(string value);
        partial void OnGradeChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                if (object.Equals(this.CreatedBy, value))
                {
                    return;
                }
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property Created in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                if (object.Equals(this.Created, value))
                {
                    return;
                }
                this._Created = value;
                this.OnCreatedChanged();
                this.OnPropertyChanged("Created");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Created;
        partial void OnCreatedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                if (object.Equals(this.ModifiedBy, value))
                {
                    return;
                }
                this._ModifiedBy = value;
                this.OnModifiedByChanged();
                this.OnPropertyChanged("ModifiedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property Modified in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return this._Modified;
            }
            set
            {
                this.OnModifiedChanging(value);
                if (object.Equals(this.Modified, value))
                {
                    return;
                }
                this._Modified = value;
                this.OnModifiedChanged();
                this.OnPropertyChanged("Modified");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Modified;
        partial void OnModifiedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedChanged();
        /// <summary>
        /// There are no comments for Property RowVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// There are no comments for Missions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Mission> Missions
        {
            get
            {
                this.@__Missions.EnsureValueInitialized();
                return this._Missions;
            }
            set
            {
                this._Missions = value;
                this.OnPropertyChanged("Missions");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Mission> _Missions = new global::System.Data.Services.Client.DataServiceCollection<Mission>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.Mission in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Missions")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Mission : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Mission object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="dateDebut">Initial value of dateDebut.</param>
        /// <param name="nomClient">Initial value of nomClient.</param>
        /// <param name="mission_Commercial">Initial value of Mission_Commercial.</param>
        /// <param name="mission_Collaborateur">Initial value of Mission_Collaborateur.</param>
        /// <param name="rowVersion">Initial value of RowVersion.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Mission CreateMission(int ID, global::System.DateTime dateDebut, string nomClient, int mission_Commercial, int mission_Collaborateur, byte[] rowVersion)
        {
            Mission mission = new Mission();
            mission.Id = ID;
            mission.dateDebut = dateDebut;
            mission.nomClient = nomClient;
            mission.Mission_Commercial = mission_Commercial;
            mission.Mission_Collaborateur = mission_Collaborateur;
            mission.RowVersion = rowVersion;
            return mission;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property dateDebut in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime dateDebut
        {
            get
            {
                return this._dateDebut;
            }
            set
            {
                this.OndateDebutChanging(value);
                if (object.Equals(this.dateDebut, value))
                {
                    return;
                }
                this._dateDebut = value;
                this.OndateDebutChanged();
                this.OnPropertyChanged("dateDebut");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _dateDebut;
        partial void OndateDebutChanging(global::System.DateTime value);
        partial void OndateDebutChanged();
        /// <summary>
        /// There are no comments for Property dateFin in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> dateFin
        {
            get
            {
                return this._dateFin;
            }
            set
            {
                this.OndateFinChanging(value);
                if (object.Equals(this.dateFin, value))
                {
                    return;
                }
                this._dateFin = value;
                this.OndateFinChanged();
                this.OnPropertyChanged("dateFin");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _dateFin;
        partial void OndateFinChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OndateFinChanged();
        /// <summary>
        /// There are no comments for Property nomClient in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string nomClient
        {
            get
            {
                return this._nomClient;
            }
            set
            {
                this.OnnomClientChanging(value);
                if (object.Equals(this.nomClient, value))
                {
                    return;
                }
                this._nomClient = value;
                this.OnnomClientChanged();
                this.OnPropertyChanged("nomClient");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _nomClient;
        partial void OnnomClientChanging(string value);
        partial void OnnomClientChanged();
        /// <summary>
        /// There are no comments for Property posteOccupe in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string posteOccupe
        {
            get
            {
                return this._posteOccupe;
            }
            set
            {
                this.OnposteOccupeChanging(value);
                if (object.Equals(this.posteOccupe, value))
                {
                    return;
                }
                this._posteOccupe = value;
                this.OnposteOccupeChanged();
                this.OnPropertyChanged("posteOccupe");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _posteOccupe;
        partial void OnposteOccupeChanging(string value);
        partial void OnposteOccupeChanged();
        /// <summary>
        /// There are no comments for Property Mission_Commercial in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Mission_Commercial
        {
            get
            {
                return this._Mission_Commercial;
            }
            set
            {
                this.OnMission_CommercialChanging(value);
                if (object.Equals(this.Mission_Commercial, value))
                {
                    return;
                }
                this._Mission_Commercial = value;
                this.OnMission_CommercialChanged();
                this.OnPropertyChanged("Mission_Commercial");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Mission_Commercial;
        partial void OnMission_CommercialChanging(int value);
        partial void OnMission_CommercialChanged();
        /// <summary>
        /// There are no comments for Property Mission_Collaborateur in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Mission_Collaborateur
        {
            get
            {
                return this._Mission_Collaborateur;
            }
            set
            {
                this.OnMission_CollaborateurChanging(value);
                if (object.Equals(this.Mission_Collaborateur, value))
                {
                    return;
                }
                this._Mission_Collaborateur = value;
                this.OnMission_CollaborateurChanged();
                this.OnPropertyChanged("Mission_Collaborateur");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Mission_Collaborateur;
        partial void OnMission_CollaborateurChanging(int value);
        partial void OnMission_CollaborateurChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                if (object.Equals(this.CreatedBy, value))
                {
                    return;
                }
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property Created in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                if (object.Equals(this.Created, value))
                {
                    return;
                }
                this._Created = value;
                this.OnCreatedChanged();
                this.OnPropertyChanged("Created");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Created;
        partial void OnCreatedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                if (object.Equals(this.ModifiedBy, value))
                {
                    return;
                }
                this._ModifiedBy = value;
                this.OnModifiedByChanged();
                this.OnPropertyChanged("ModifiedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property Modified in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return this._Modified;
            }
            set
            {
                this.OnModifiedChanging(value);
                if (object.Equals(this.Modified, value))
                {
                    return;
                }
                this._Modified = value;
                this.OnModifiedChanged();
                this.OnPropertyChanged("Modified");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Modified;
        partial void OnModifiedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedChanged();
        /// <summary>
        /// There are no comments for Property RowVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// There are no comments for Commercial in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Commercial Commercial
        {
            get
            {
                this.@__Commercial.EnsureValueInitialized();
                return this._Commercial;
            }
            set
            {
                Commercial previous = this.Commercial;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._Commercial = null;
                    this.@__Commercial.OnValueSet();
                    previous.Missions.Remove(this);
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.Mission_Commercial = value.Id;
                    }
                    else
                    {
                        this.Mission_Commercial = default(int);
                    }
                }
                this._Commercial = value;
                this.@__Commercial.OnValueSet();
                if ((value != null))
                {
                    value.@__Missions.Add(this);
                }
                this.___OnPropertyChanged("Commercial");
                this.OnPropertyChanged("Commercial");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Commercial _Commercial;
        /// <summary>
        /// There are no comments for Collaborateur in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Collaborateur Collaborateur
        {
            get
            {
                this.@__Collaborateur.EnsureValueInitialized();
                return this._Collaborateur;
            }
            set
            {
                Collaborateur previous = this.Collaborateur;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._Collaborateur = null;
                    this.@__Collaborateur.OnValueSet();
                    previous.Missions.Remove(this);
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.Mission_Collaborateur = value.Id;
                    }
                    else
                    {
                        this.Mission_Collaborateur = default(int);
                    }
                }
                this._Collaborateur = value;
                this.@__Collaborateur.OnValueSet();
                if ((value != null))
                {
                    value.@__Missions.Add(this);
                }
                this.___OnPropertyChanged("Collaborateur");
                this.OnPropertyChanged("Collaborateur");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Collaborateur _Collaborateur;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
