

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// Cette table contient tous les collaborateurs !
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    public sealed partial class Collaborateur : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Collaborateur entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Collaborateur()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Collaborateur(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Collaborateur> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Collaborateur.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Collaborateur_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Collaborateur_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Collaborateur.DetailsClass.GetValue(this, global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.Collaborateur.DetailsClass.SetValue(this, global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string nom
        {
            get
            {
                return global::LightSwitchApplication.Collaborateur.DetailsClass.GetValue(this, global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties.nom);
            }
            set
            {
                global::LightSwitchApplication.Collaborateur.DetailsClass.SetValue(this, global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties.nom, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void nom_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void nom_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void nom_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string prenom
        {
            get
            {
                return global::LightSwitchApplication.Collaborateur.DetailsClass.GetValue(this, global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties.prenom);
            }
            set
            {
                global::LightSwitchApplication.Collaborateur.DetailsClass.SetValue(this, global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties.prenom, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void prenom_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void prenom_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void prenom_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string email
        {
            get
            {
                return global::LightSwitchApplication.Collaborateur.DetailsClass.GetValue(this, global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties.email);
            }
            set
            {
                global::LightSwitchApplication.Collaborateur.DetailsClass.SetValue(this, global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties.email, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void email_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void email_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void email_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string portable
        {
            get
            {
                return global::LightSwitchApplication.Collaborateur.DetailsClass.GetValue(this, global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties.portable);
            }
            set
            {
                global::LightSwitchApplication.Collaborateur.DetailsClass.SetValue(this, global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties.portable, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void portable_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void portable_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void portable_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] Portrait
        {
            get
            {
                return global::LightSwitchApplication.Collaborateur.DetailsClass.GetValue(this, global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties.Portrait);
            }
            set
            {
                global::LightSwitchApplication.Collaborateur.DetailsClass.SetValue(this, global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties.Portrait, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Portrait_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Portrait_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Portrait_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CreatedBy
        {
            get
            {
                return global::LightSwitchApplication.Collaborateur.DetailsClass.GetValue(this, global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties.CreatedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return global::LightSwitchApplication.Collaborateur.DetailsClass.GetValue(this, global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties.Created);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModifiedBy
        {
            get
            {
                return global::LightSwitchApplication.Collaborateur.DetailsClass.GetValue(this, global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties.ModifiedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return global::LightSwitchApplication.Collaborateur.DetailsClass.GetValue(this, global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties.Modified);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.Collaborateur.DetailsClass.GetValue(this, global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.Collaborateur.DetailsClass.SetValue(this, global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Mission> Missions
        {
            get
            {
                return global::LightSwitchApplication.Collaborateur.DetailsClass.GetValue(this, global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties.Missions);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Mission> MissionsQuery
        {
            get
            {
                return global::LightSwitchApplication.Collaborateur.DetailsClass.GetQuery(this, global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties.Missions);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Collaborateur,
                global::LightSwitchApplication.Collaborateur.DetailsClass,
                global::LightSwitchApplication.Collaborateur.DetailsClass.IImplementation,
                global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass>.Entry
                __CollaborateurEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass>.Entry(
                    global::LightSwitchApplication.Collaborateur.DetailsClass.__Collaborateur_CreateNew,
                    global::LightSwitchApplication.Collaborateur.DetailsClass.__Collaborateur_Created,
                    global::LightSwitchApplication.Collaborateur.DetailsClass.__Collaborateur_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Collaborateur __Collaborateur_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Collaborateur> es)
            {
                return new global::LightSwitchApplication.Collaborateur(es);
            }
            private static void __Collaborateur_Created(global::LightSwitchApplication.Collaborateur e)
            {
                e.Collaborateur_Created();
            }
            private static bool __Collaborateur_AllowSaveWithErrors(global::LightSwitchApplication.Collaborateur e)
            {
                bool result = false;
                e.Collaborateur_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, string> nom
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties.nom) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, string> prenom
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties.prenom) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, string> email
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties.email) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, string> portable
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties.portable) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, byte[]> Portrait
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties.Portrait) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, string> CreatedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties.CreatedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Created
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties.Created) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, string> ModifiedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties.ModifiedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Modified
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties.Modified) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, global::LightSwitchApplication.Mission> Missions
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties.Missions) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, global::LightSwitchApplication.Mission>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new string nom { get; set; }
                new string prenom { get; set; }
                new string email { get; set; }
                new string portable { get; set; }
                new byte[] Portrait { get; set; }
                new string CreatedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Created { get; }
                new string ModifiedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Modified { get; }
                new byte[] RowVersion { get; set; }
                new global::System.Collections.IEnumerable Missions { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Collaborateur.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, int>.Data> c, global::LightSwitchApplication.Collaborateur.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Collaborateur e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Collaborateur e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Collaborateur.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.Collaborateur.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Collaborateur e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, string>.Entry
                    nom = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, string>.Entry(
                        "nom",
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._nom_Stub,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._nom_ComputeIsReadOnly,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._nom_Validate,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._nom_GetImplementationValue,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._nom_SetImplementationValue,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._nom_OnValueChanged);
                private static void _nom_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Collaborateur.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, string>.Data> c, global::LightSwitchApplication.Collaborateur.DetailsClass d, object sf)
                {
                    c(d, ref d._nom, sf);
                }
                private static bool _nom_ComputeIsReadOnly(global::LightSwitchApplication.Collaborateur e)
                {
                    bool result = false;
                    e.nom_IsReadOnly(ref result);
                    return result;
                }
                private static void _nom_Validate(global::LightSwitchApplication.Collaborateur e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.nom_Validate(r);
                }
                private static string _nom_GetImplementationValue(global::LightSwitchApplication.Collaborateur.DetailsClass d)
                {
                    return d.ImplementationEntity.nom;
                }
                private static void _nom_SetImplementationValue(global::LightSwitchApplication.Collaborateur.DetailsClass d, string v)
                {
                    d.ImplementationEntity.nom = v;
                }
                private static void _nom_OnValueChanged(global::LightSwitchApplication.Collaborateur e)
                {
                    e.nom_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, string>.Entry
                    prenom = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, string>.Entry(
                        "prenom",
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._prenom_Stub,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._prenom_ComputeIsReadOnly,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._prenom_Validate,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._prenom_GetImplementationValue,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._prenom_SetImplementationValue,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._prenom_OnValueChanged);
                private static void _prenom_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Collaborateur.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, string>.Data> c, global::LightSwitchApplication.Collaborateur.DetailsClass d, object sf)
                {
                    c(d, ref d._prenom, sf);
                }
                private static bool _prenom_ComputeIsReadOnly(global::LightSwitchApplication.Collaborateur e)
                {
                    bool result = false;
                    e.prenom_IsReadOnly(ref result);
                    return result;
                }
                private static void _prenom_Validate(global::LightSwitchApplication.Collaborateur e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.prenom_Validate(r);
                }
                private static string _prenom_GetImplementationValue(global::LightSwitchApplication.Collaborateur.DetailsClass d)
                {
                    return d.ImplementationEntity.prenom;
                }
                private static void _prenom_SetImplementationValue(global::LightSwitchApplication.Collaborateur.DetailsClass d, string v)
                {
                    d.ImplementationEntity.prenom = v;
                }
                private static void _prenom_OnValueChanged(global::LightSwitchApplication.Collaborateur e)
                {
                    e.prenom_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, string>.Entry
                    email = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, string>.Entry(
                        "email",
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._email_Stub,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._email_ComputeIsReadOnly,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._email_Validate,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._email_GetImplementationValue,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._email_SetImplementationValue,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._email_OnValueChanged);
                private static void _email_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Collaborateur.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, string>.Data> c, global::LightSwitchApplication.Collaborateur.DetailsClass d, object sf)
                {
                    c(d, ref d._email, sf);
                }
                private static bool _email_ComputeIsReadOnly(global::LightSwitchApplication.Collaborateur e)
                {
                    bool result = false;
                    e.email_IsReadOnly(ref result);
                    return result;
                }
                private static void _email_Validate(global::LightSwitchApplication.Collaborateur e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.email_Validate(r);
                }
                private static string _email_GetImplementationValue(global::LightSwitchApplication.Collaborateur.DetailsClass d)
                {
                    return d.ImplementationEntity.email;
                }
                private static void _email_SetImplementationValue(global::LightSwitchApplication.Collaborateur.DetailsClass d, string v)
                {
                    d.ImplementationEntity.email = v;
                }
                private static void _email_OnValueChanged(global::LightSwitchApplication.Collaborateur e)
                {
                    e.email_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, string>.Entry
                    portable = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, string>.Entry(
                        "portable",
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._portable_Stub,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._portable_ComputeIsReadOnly,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._portable_Validate,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._portable_GetImplementationValue,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._portable_SetImplementationValue,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._portable_OnValueChanged);
                private static void _portable_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Collaborateur.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, string>.Data> c, global::LightSwitchApplication.Collaborateur.DetailsClass d, object sf)
                {
                    c(d, ref d._portable, sf);
                }
                private static bool _portable_ComputeIsReadOnly(global::LightSwitchApplication.Collaborateur e)
                {
                    bool result = false;
                    e.portable_IsReadOnly(ref result);
                    return result;
                }
                private static void _portable_Validate(global::LightSwitchApplication.Collaborateur e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.portable_Validate(r);
                }
                private static string _portable_GetImplementationValue(global::LightSwitchApplication.Collaborateur.DetailsClass d)
                {
                    return d.ImplementationEntity.portable;
                }
                private static void _portable_SetImplementationValue(global::LightSwitchApplication.Collaborateur.DetailsClass d, string v)
                {
                    d.ImplementationEntity.portable = v;
                }
                private static void _portable_OnValueChanged(global::LightSwitchApplication.Collaborateur e)
                {
                    e.portable_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, byte[]>.Entry
                    Portrait = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, byte[]>.Entry(
                        "Portrait",
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._Portrait_Stub,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._Portrait_ComputeIsReadOnly,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._Portrait_Validate,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._Portrait_GetImplementationValue,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._Portrait_SetImplementationValue,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._Portrait_OnValueChanged);
                private static void _Portrait_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Collaborateur.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.Collaborateur.DetailsClass d, object sf)
                {
                    c(d, ref d._Portrait, sf);
                }
                private static bool _Portrait_ComputeIsReadOnly(global::LightSwitchApplication.Collaborateur e)
                {
                    bool result = false;
                    e.Portrait_IsReadOnly(ref result);
                    return result;
                }
                private static void _Portrait_Validate(global::LightSwitchApplication.Collaborateur e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Portrait_Validate(r);
                }
                private static byte[] _Portrait_GetImplementationValue(global::LightSwitchApplication.Collaborateur.DetailsClass d)
                {
                    return d.ImplementationEntity.Portrait;
                }
                private static void _Portrait_SetImplementationValue(global::LightSwitchApplication.Collaborateur.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.Portrait = v;
                }
                private static void _Portrait_OnValueChanged(global::LightSwitchApplication.Collaborateur e)
                {
                    e.Portrait_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, string>.Entry
                    CreatedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, string>.Entry(
                        "CreatedBy",
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._CreatedBy_Stub,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._CreatedBy_Validate,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged);
                private static void _CreatedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Collaborateur.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, string>.Data> c, global::LightSwitchApplication.Collaborateur.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedBy, sf);
                }
                private static bool _CreatedBy_ComputeIsReadOnly(global::LightSwitchApplication.Collaborateur e)
                {
                    bool result = false;
                    e.CreatedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedBy_Validate(global::LightSwitchApplication.Collaborateur e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedBy_Validate(r);
                }
                private static string _CreatedBy_GetImplementationValue(global::LightSwitchApplication.Collaborateur.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedBy;
                }
                private static void _CreatedBy_OnValueChanged(global::LightSwitchApplication.Collaborateur e)
                {
                    e.CreatedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Created = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Created",
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._Created_Stub,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._Created_ComputeIsReadOnly,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._Created_Validate,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._Created_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._Created_OnValueChanged);
                private static void _Created_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Collaborateur.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.Collaborateur.DetailsClass d, object sf)
                {
                    c(d, ref d._Created, sf);
                }
                private static bool _Created_ComputeIsReadOnly(global::LightSwitchApplication.Collaborateur e)
                {
                    bool result = false;
                    e.Created_IsReadOnly(ref result);
                    return result;
                }
                private static void _Created_Validate(global::LightSwitchApplication.Collaborateur e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Created_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Created_GetImplementationValue(global::LightSwitchApplication.Collaborateur.DetailsClass d)
                {
                    return d.ImplementationEntity.Created;
                }
                private static void _Created_OnValueChanged(global::LightSwitchApplication.Collaborateur e)
                {
                    e.Created_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, string>.Entry
                    ModifiedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, string>.Entry(
                        "ModifiedBy",
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._ModifiedBy_Stub,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._ModifiedBy_Validate,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged);
                private static void _ModifiedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Collaborateur.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, string>.Data> c, global::LightSwitchApplication.Collaborateur.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedBy, sf);
                }
                private static bool _ModifiedBy_ComputeIsReadOnly(global::LightSwitchApplication.Collaborateur e)
                {
                    bool result = false;
                    e.ModifiedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedBy_Validate(global::LightSwitchApplication.Collaborateur e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedBy_Validate(r);
                }
                private static string _ModifiedBy_GetImplementationValue(global::LightSwitchApplication.Collaborateur.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedBy;
                }
                private static void _ModifiedBy_OnValueChanged(global::LightSwitchApplication.Collaborateur e)
                {
                    e.ModifiedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Modified = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Modified",
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._Modified_Stub,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._Modified_ComputeIsReadOnly,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._Modified_Validate,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._Modified_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._Modified_OnValueChanged);
                private static void _Modified_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Collaborateur.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.Collaborateur.DetailsClass d, object sf)
                {
                    c(d, ref d._Modified, sf);
                }
                private static bool _Modified_ComputeIsReadOnly(global::LightSwitchApplication.Collaborateur e)
                {
                    bool result = false;
                    e.Modified_IsReadOnly(ref result);
                    return result;
                }
                private static void _Modified_Validate(global::LightSwitchApplication.Collaborateur e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Modified_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Modified_GetImplementationValue(global::LightSwitchApplication.Collaborateur.DetailsClass d)
                {
                    return d.ImplementationEntity.Modified;
                }
                private static void _Modified_OnValueChanged(global::LightSwitchApplication.Collaborateur e)
                {
                    e.Modified_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Collaborateur.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.Collaborateur.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.Collaborateur e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.Collaborateur e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.Collaborateur.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.Collaborateur.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.Collaborateur e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, global::LightSwitchApplication.Mission>.Entry
                    Missions = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, global::LightSwitchApplication.Mission>.Entry(
                        "Missions",
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._Missions_Stub,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._Missions_GetReferencedEntities,
                        global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties._Missions_GetEntityCollection);
                private static void _Missions_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Collaborateur.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, global::LightSwitchApplication.Mission>.Data> c, global::LightSwitchApplication.Collaborateur.DetailsClass d, object sf)
                {
                    c(d, ref d._Missions, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Mission> _Missions_GetReferencedEntities(global::LightSwitchApplication.Collaborateur.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Mission, global::LightSwitchApplication.Mission.DetailsClass>(global::LightSwitchApplication.Collaborateur.DetailsClass.PropertySetProperties.Missions, ref d._Missions);
                }
                private static global::System.Collections.IEnumerable _Missions_GetEntityCollection(global::LightSwitchApplication.Collaborateur.DetailsClass d)
                {
                    return d.ImplementationEntity.Missions;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, string>.Data _nom;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, string>.Data _prenom;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, string>.Data _email;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, string>.Data _portable;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, byte[]>.Data _Portrait;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, string>.Data _CreatedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Created;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, string>.Data _ModifiedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Modified;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Collaborateur, global::LightSwitchApplication.Collaborateur.DetailsClass, global::LightSwitchApplication.Mission>.Data _Missions;
            
        }
    
        #endregion
    }
    
    #endregion
}
